version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.24.0
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.6.0
    - 7.7.0
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.7
